services:
  - type: web
    name: academia-validator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000